# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_if = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_if.setGeometry(QtCore.QRect(290, 110, 221, 111))
        self.txt_if.setObjectName("txt_if")
        self.txt_si = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_si.setGeometry(QtCore.QRect(290, 270, 221, 111))
        self.txt_si.setObjectName("txt_si")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 240, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_si = QtWidgets.QPushButton(self.centralwidget)
        self.btn_si.setGeometry(QtCore.QRect(250, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_si.setFont(font)
        self.btn_si.setObjectName("btn_si")
        self.btn_ve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ve.setGeometry(QtCore.QRect(450, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_ve.setFont(font)
        self.btn_ve.setObjectName("btn_ve")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 30, 101, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DEMO ECC CIPHER"))
        self.label_6.setText(_translate("MainWindow", "Signature"))
        self.label_7.setText(_translate("MainWindow", "Ifnormation"))
        self.btn_si.setText(_translate("MainWindow", "Sign"))
        self.btn_ve.setText(_translate("MainWindow", "Verify"))
        self.pushButton.setText(_translate("MainWindow", "Generate Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
